/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2022-2026 iceman (wqliceman@gmail.com)
 * GitHub: iceman
 * This file is part of ab_plc_cip_net.
 */

#ifndef __H_AB_CIP_PRIVATE_H__
#define __H_AB_CIP_PRIVATE_H__
#include "typedef.h"

/// <summary>
/// Register session command bytes.
/// </summary>
const byte g_registered_command[] =
{
	0x65, 0x00,										// Register request
	0x04, 0x00,										// Command data length (bytes)
	0x00, 0x00, 0x00, 0x00,							// Session handle, initial value 0x00000000
	0x00, 0x00, 0x00, 0x00,							// Status, initial value 0x00000000 (good)
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // Sender context
	0x00, 0x00, 0x00, 0x00,							// Options, default 0x00000000
	0x01, 0x00,										// Protocol version (0x0001)
	0x00, 0x00										// Option flags (0x0000)
};

// Session handle (generated by AB PLC)
uint32 g_session;

byte g_plc_slot;

#endif //__H_AB_CIP_PRIVATE_H__
